### ISSUE TITLE
Trying to figure this one out

### ISSUE THREAD

**Issue by TheFuzz4** [samwiseg00/plex#1]
So I cloned your repo to my /usr/local/src and then I setup a symlink to /opt for the scripts section.  Is there any changes to the agent conf file for zabbix that I need to make in order for this to work?  Zabbix is still showing that its trying to pull the logs from /var when thats not an option for me since my plex runs in docker.  I updated the config python to have the correct values in it for tautulli and plex with api and token keys and the correct domains.  Ran the python scripts by hand and they return the data but its like zabbix isn't looking at the right place. This is my first real active check done with zabbix so it might be a learning curve issue on my end as well.  Thank you for putting together such an awesome template.

**Comment by samwiseg0** [comment]
You may need to update the path inside the agent .conf file. It should reflect where the scripts are located.

https://github.com/samwiseg0/plex/blob/master/debug_stats_monitoring/zabbix-template/plex_health_stats.conf

**Comment by TheFuzz4** [comment]
yeah I just realized what I did wrong.  I copied the conf file from there to the /etc/zabbix/zabbix_agentd.conf/ and Now waiting to see if it picks it up.

**Comment by samwiseg0** [comment]
More than likely you will need to put it in `/etc/zabbix/zabbix_agentd.d/`. Also you have to restart the agent. The agent logs should also help in seeing if there are any errors with the checks.

**Comment by TheFuzz4** [comment]
Thank you very much, yeah been tailing the log files and kept seeing 
`1159825:20181212:185738.286 active check "log[/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log,(?i)(?:Permission|error)]" is not supported: Cannot obtain information for file "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.subzero.log": [2] No such file or directory
1159825:20181212:185738.286 active check "log[/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log]" is not supported: Cannot obtain information for file "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log": [2] No such file or directory
1159825:20181212:185738.287 active check "log[/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log,(?i)(?:slow|error)]" is not supported: Cannot obtain information for file "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log": [2] No such file or directory` 
which is why I posted here :) but now I'm waiting for the next round to go through and I hope to see it doing the checks.

**Comment by samwiseg0** [comment]
Looks like zabbix and scripts cannot access those files. Check permissions.

**Comment by TheFuzz4** [comment]
No its because I'm using docker and my plex logs are in a different location.  Edited the items in zabbix to point at the correct path and disabled the subzero check since I'm not using that plugin.  I think I'm headed in the right direction now.

**Comment by TheFuzz4** [comment]
Ok so making headway

`root@deadpool04:/opt/plex/debug_stats_monitoring/scripts# ./plex_health_stats_operations.py
Traceback (most recent call last):
  File "./plex_health_stats_operations.py", line 13, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'
root@deadpool04:/opt/plex/debug_stats_monitoring/scripts# pip install xmltodict
Requirement already satisfied: xmltodict in /usr/local/lib/python2.7/dist-packages`

But not quite sure how to get around this as the requirement is installed

**Comment by samwiseg0** [comment]
You have to use python 3.6+ not 2.7

**Comment by TheFuzz4** [comment]
yeah this was weird even calling it with python3 and python3.6 threw that error.  Ran it with just python and then it was good. I don't get it either lol

**Comment by TheFuzz4** [comment]
Ok updated pip to pip3 (I'm using ubuntu) and now I have xmltodict loaded and I think we might be off to the races now.  Waiting for zabbix to realize that we're ok.

**Comment by TheFuzz4** [comment]
So for those who come across any of this on Ubuntu.  Install python 3.6 install pip3.  With pip3 do pip3 install xmltodict
Copy the conf file from zabbix-template folder to the zabbix agent conf.d dir so it will be loaded when you restart the agent.  Make any necessary adjustments to the items in zabbix if you have different paths.

**Comment by samwiseg0** [comment]
Thanks for the update and closing this out
