### ISSUE TITLE
Issues running the script

### ISSUE THREAD

**Issue by inscribeme** [samwiseg00/plex#2]
Hi samwiseg0,

Thanks for the script and the detailed notes. I added the script to a local folder on the CentOS PLEX server and added the script to the DVR settings _/path/PlexPostProc.sh_. FFMPEG never kicks in after records end (commercial removal not enabled) and LOGS show "exit code for process 1160 is 127 (failure)". I am able to manually run FFMPEG from the CLI without issues (_ffmpeg -i /path/file.ts  -s hd720 -c:v libx264 -preset veryfast -vf yadif -c:a copy /path/test.mkv_).

I am technical but not experienced in scripts, programming or even the LINUX CLI. I read in your script description that USAGE should be **'PlexPostProc.sh %1'** . Does that mean that I need to add the **%1** (and even the **'**) in the DVR settings (ie; _/path/'PlexPostProc.sh %1'_)? 

Any help with this would be greatly appreciated.

THANKS!

**Comment by samwiseg0** [comment]
Have you tried using the full path for ffmpeg in the script?
