### ISSUE TITLE
How tu use that ?

### ISSUE THREAD

**Issue by barto95100** [samwiseg00/plex#3]
Hi,

How tu use that ? I have 3 plex Server and Zabbix Server/Proxy

Thank's for your help

**Comment by samwiseg0** [comment]
How to use what?

**Comment by barto95100** [comment]
collection of scripts and services to monitor plex with Zabbix

**Comment by samwiseg0** [comment]
Have you walked through the readme? They work like other scripts with zabbix. All the files you need are in the repo.

**Comment by barto95100** [comment]
Ok

It's necessary to install a agent on PlexServer and install script on this server or zabbix server pool the plex directly if script is on server zabbix ?

**Comment by samwiseg0** [comment]
All scripts are installed on the plex server. Yes, you have to have the zabbix agent on the plex server. That is outlined in the README.
